export interface Project {
  slug: string;
  title: string;
  description: string;
  overview: string;
  features: string[];
  codeSnippet?: string;
  codeDescription?: string;
  screenshots?: string[];
  techStack: string[];
  challenges: string;
  reflection: string;
  color: string;
}

export const projectsData: Project[] = [
  {
    slug: "linear-regression-plant-growth",
    title: "Linear Regression - Plant Growth",
    description: "A machine learning activity exploring the relationship between temperature and plant growth rates.",
    overview: "This project uses linear regression to determine the best temperature range for plant growth. Synthetic data is used, generated by using the linspace() function, a linear model is trained and evaluated against it, and the results are visualized on a scatter plot. This project served as a first hands-on introduction to machine learning concepts and scikit-learn.",
    features: [
      "Synthetic Dataset Generation with NumPy",
      "Linear Regression Model Training via scikit-learn",
      "Model Evaluation using MAE, MSE, RMSE, and R² Score",
      "Data Visualization with Matplotlib"
    ],
    codeSnippet: `# Train a linear regression model on temperature vs. growth data
      model = LinearRegression()
      model.fit(temperatures, growth)
      growth_pred = model.predict(temperatures)

      # Evaluate model performance
      mae  = mean_absolute_error(growth, growth_pred)
      mse  = mean_squared_error(growth, growth_pred)
      rmse = np.sqrt(mse)
      r2   = r2_score(growth, growth_pred)

      print('Mean Absolute Error:', mae)
      print('R2 Score:', r2)`,
    codeDescription: "After reshaping the temperature array into a 2D column vector, the model is fit and used to generate predictions. The four evaluation metrics measured how accurate the model was, although each one was for a different purpose, it nevertheless measured how effective the model was.",
    screenshots: [],
    techStack: ["Python", "NumPy", "scikit-learn", "Matplotlib", "Google Colab"],
    challenges: "As a first encounter with machine learning, both the concepts and the tooling were unfamiliar to me. Learning and understanding the syntax, why certain code blocks existed, and how to graph the values were all learned  through this project.",
    reflection: "This was my entry point into machine learning, and it made me genuinely curious about the field. Seeing a model learn a pattern from data and then visualize it as a line cutting through a scatter plot made the concept click in a way that theory alone wouldn't have. It’s the foundation for every ML project I've worked on since.",
    color: "bg-[oklch(0.88_0.10_250)]" // Pastel Blue
  },
  {
    slug: "neural-network-plant-growth",
    title: "Linear Regression Using Neural Network - Plant Growth",
    description: "Revisiting the plant growth problem using a neural network instead of a linear model.",
    overview: "This activity used the same plant growth dataset as the linear regression project, but this time using a neural network model. The goal was to see how a different approach handles the same data — and whether it does a better job following the curve in the numbers.",
    features: [
      "Multi-Layer Perceptron Regression with scikit-learn",
      "Feature Scaling via StandardScaler",
      "Sklearn Pipeline for Streamlined Preprocessing",
      "Model Evaluation using MAE, MSE, RMSE, and R² Score"
    ],
    codeSnippet: `# Pipeline that scales the data then runs it through the network
      model = Pipeline([
          ('scaler', StandardScaler()),
          ('nn', MLPRegressor(
              hidden_layer_sizes=(50, 50),
              activation='relu',
              solver='adam',
              max_iter=5000,
              random_state=42
          ))
      ])

      model.fit(X, y)
      y_pred = model.predict(X)`,
    codeDescription: "The Pipeline handles scaling and training in one step. The network has two layers of 50 neurons and uses ReLU activation.",
    screenshots: [],
    techStack: ["Python", "NumPy", "MLPRegressor", "scikit-learn", "Matplotlib", "Google Colab"],
    challenges: "Coming from linear regression, this felt like a big jump. There were a lot of new parameters to understand — hidden layers, activation functions, solvers — and it wasn't immediately obvious what each one was doing or why it mattered.",
    reflection: "I came out of this realizing that different models think about data differently. The neural network curved where the linear model stayed flat, and that small visual difference said a lot about why model choice matters.",
    color: "bg-[oklch(0.88_0.10_80)]" // Pastel Yellow
  },
  {
    slug: "iris-classification",
    title: "Iris Classification",
    description: "Classifying iris flowers by species using a k-Nearest Neighbors model connected to a live UI via Anvil.",
    overview: "This activity uses the classic Iris dataset to classify flowers into three species based on their sepal and petal measurements. A kNN model handles the predictions, and the whole thing is connected to an Anvil frontend — making it the first project where the model was actually usable through a real interface.",
    features: [
      "k-Nearest Neighbors Classification via scikit-learn",
      "Train/Test Split for Model Evaluation",
      "Accuracy Score, Confusion Matrix, and Classification Report",
      "Live Frontend Integration via Anvil Uplink"
    ],
    codeSnippet: `# Train the kNN model and expose it as a callable function
      knn = KNeighborsClassifier(n_neighbors=10)
      knn.fit(X, y)

      @anvil.server.callable
      def predict_iris(sepal_length, sepal_width, petal_length, petal_width):
          classification = knn.predict([[sepal_length, sepal_width, petal_length, petal_width]])
    return iris.target_names[classification][0]`,
    codeDescription: "The model is trained on the full dataset, then wrapped in an Anvil-callable function. This lets the Anvil frontend send measurements and get a species prediction back in real time, connecting the model to an actual user-facing interface.",
    screenshots: [],
    techStack: ["Python", "scikit-learn", "KNeighborsClassifier", "Matplotlib", "Anvil", "Google Colab"],
    challenges: "Connecting the model to Anvil was new territory. It was the first time I had to use and connect the model outside of the Colab notebook, which added a layer of complexity I hadn't dealt with before.",
    reflection: "Linking the model to a UI made everything feel more real. Up until this point, the projects had only been contained inside a notebook. Inputting the flower measurements myself and get a prediction back made me understand how machine learning fits into actual products.",
    color: "bg-[oklch(0.88_0.10_140)]" // Pastel Green
  },
  {
    slug: "iris-classification-model-selection",
    title: "Iris Classification Model Selection ",
    description: "Revisiting the iris dataset but this time using a neural network, then compare it against against the kNN model from the previous activity.",
    overview: "Same dataset as the kNN project, different model. This time we used an MLP classifier and compared the results side by side. Both models landed at 96.67% accuracy, but the MLP did a better job on the harder classes. I also noticed the two models were tested on different data splits, which made the comparison a bit unfair.",
    features: [
      "MLP Classification via scikit-learn",
      "Stratified Train/Test Split for Balanced Evaluation",
      "Accuracy Score, Confusion Matrix, and Classification Report",
      "Head-to-head Model Comparison Against kNN"
    ],
    codeSnippet: `# Train the MLP classifier
      mlp = MLPClassifier(
          hidden_layer_sizes=(10,),
          activation='relu',
          solver='adam',
          max_iter=500,
          random_state=42,
      )
      mlp.fit(X_train, y_train)
      y_pred = mlp.predict(X_test)

      print("Accuracy:", accuracy_score(y_test, y_pred))
      print("Confusion Matrix:\\n", confusion_matrix(y_test, y_pred))
      print("Classification Report:\\n", classification_report(y_test, y_pred))`,
    codeDescription: "One hidden layer of 10 neurons is enough for a simple three-class problem like this. Adding stratify to the split makes sure each species shows up proportionally in both the training and test sets.",
    screenshots: [],
    techStack: ["Python", "scikit-learn", "MLPClassifier", "Matplotlib", "Google Colab"],
    challenges: "The syntax was still new but nothing really blocked me. The harder part was understanding that two models can have the same accuracy score but still perform differently depending on which classes you look at.",
    reflection: "This was the first time I had to pick a winner between two models. It made me realize that accuracy is just one number. To actually understand how a model is doing, you have to dig into the breakdown by class.",
    color: "bg-[oklch(0.85_0.12_340)]" // Pastel Pink
  },
  {
    slug: "boston-housing-price-prediction",
    title: "Boston Housing Price Prediction",
    description: "Predicting housing prices using a neural network, learning about feature selection and preprocessing, and connecting the model to a live UI via Anvil.",
    overview: "This project combined both Boston Housing activities, Linear Regression and Neural Network, into one. We explored the dataset using correlation matrices and heatmaps to pick the three features that impacted price the most, scaled the data using StandardScaler, then trained a neural network to make predictions. The model was also connected to an Anvil frontend so predictions could be made through an interface. The activity also came with guided questions that helped us to actually understand each step rather than just run the code.",
    features: [
      "Exploratory Data Analysis with Seaborn",
      "Feature Selection via Correlation Heatmap",
      "Data Preprocessing with StandardScaler",
      "Neural Network Regression with Keras",
      "Training and Validation Loss Visualization",
      "Live Price Prediction via Anvil UI"
    ],
    codeSnippet: `# Scale features and build the neural network
      scaler = StandardScaler()
      X_train = scaler.fit_transform(X_train)
      X_test = scaler.transform(X_test)

      model = Sequential()
      model.add(Dense(16, activation='relu', input_shape=(X_train.shape[1],)))
      model.add(Dense(8, activation='relu'))
      model.add(Dense(1))

      model.compile(optimizer='adam', loss='mse')
      model.fit(X_train, y_train, validation_split=0.2, epochs=300, batch_size=16)`,
    codeDescription: "StandardScaler normalizes the input features before they reach the network, which helps the model train more smoothly. The network has two hidden layers followed by a single output neuron for the price prediction. Training for 300 epochs instead of 100 showed only a small improvement in loss, which hinted that the model was close to its limit with these features.",
    screenshots: [],
    techStack: ["Python", "scikit-learn", "Keras", "StandardScaler", "MLPRegressor", "Seaborn", "Matplotlib", "Pandas", "Anvil", "Google Colab"],
    challenges: "The guided questions in the activity made it harder to just skim through the code. Having to stop and answer things like what the loss was at epoch 100, or how many input features the model expected, forced a closer look at what was actually happening at each step.",
    reflection: "I came out of this knowing that preprocessing is not just a box to check. Scaling the data, picking the right features, and understanding what the loss curve is telling you all affect how well the model performs. There is still more to explore there.",
    color: "bg-[oklch(0.88_0.10_250)]" // Pastel Blue
  },
  {
    slug: "boston-housing-model-improvement",
    title: "Boston Housing: Model Improvement & Deployment",
    description: "Focusing on improving the Boston Housing model and deploying it as a live web app using Streamlit.",
    overview: "This activity picked up where the previous Boston housing model left. The first part was about improving the existing neural network by testing different configurations, adding extra layers and early stopping, then comparing all three versions side by side to find the best one. The second part was about deployment, saving the trained model as a Keras file and connecting it to a Streamlit web app.",
    features: [
      "Early Stopping to Prevent Overfitting",
      "Model Comparison Across Three Configurations",
      "Additional Hidden Layer Experimentation",
      "Model Export as Keras File",
      "Web App Deployment via Streamlit",
      "Live Predictions through Streamlit web app deployment"
    ],
    codeSnippet: `# Early stopping configuration
      early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

      # Compare three model configurations
      results = []
      results.append(["Early Stop", mae, mse, rmse, r2])
      results.append(["Early Stop + Extra Layer", mae, mse, rmse, r2])
      results.append(["Original", mae, mse, rmse, r2])

      # Pick the best one based on lowest RMSE
      results_df = pd.DataFrame(results, columns=["Model", "MAE", "MSE", "RMSE", "R2"])
      best_model = results_df.loc[results_df["RMSE"].idxmin()]

      # Save the model for deployment
      model.save("boston_model.keras")
      joblib.dump(scaler, "scaler.save")`,
    codeDescription: "Three versions of the model are trained and logged into a results table. Early stopping cuts training short when the validation loss stops improving, which helps avoid overfitting. Once the best model is identified, it gets saved as a Keras file alongside the scaler so they can both be loaded for the Streamlit app.",
    screenshots: [],
    techStack: ["Python", "Keras", "TensorFlow", "scikit-learn", "StandardScaler", "Streamlit", "Anvil", "Joblib", "Pandas", "Google Colab"],
    challenges: "Figuring out which model configuration actually performed better took some trial and error. The deployment side was just as tricky, getting the saved model and scaler to load correctly in Streamlit, and making sure the inputs were scaled the same way during prediction as they were during training.",
    reflection: "This was the first time I saw a project through from start to finish. Building the model was one thing, but improving it, saving it, and putting it on a website made the whole process more complete. It changed how I think about machine learning projects.",
    color: "bg-[oklch(0.88_0.10_140)]" // Pastel Green
  },
  {
    slug: "cnn-image-classification",
    title: "CNN Image Classification",
    description: "Using  a Convolutional Neural Network to classify images from the CIFAR-10 dataset, also focused on improving the model.",
    overview: "This activity introduced image classification using a CNN trained on CIFAR-10, a dataset of 60,000 images across 10 categories like cats, airplanes, and trucks. The first version was barebones, 5 epochs, no dropout, no optimizer tuning. The second version added 20 epochs, dropout, and a tuned Adam optimizer. At the end, we tested the model on our own images to see how it performed in practice.",
    features: [
      "CNN Architecture with Conv2D and MaxPooling Layers",
      "Image Normalization for Training and Testing",
      "Dropout Layer to Reduce Overfitting",
      "Adam Optimizer with Custom Learning Rate",
      "Custom Image Prediction from Local Files",
      "Model Comparison Across Two Configurations"
    ],
    codeSnippet: `# Normalize images and build the CNN
    X_train = X_train / 255.0
    X_test = X_test / 255.0

    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[32,32,3]))
    model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2, padding='valid'))
    model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(units=128, activation='relu'))
    model.add(tf.keras.layers.Dense(units=10, activation='softmax'))
    model.add(tf.keras.layers.Dropout(0.2))

    optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])
    model.fit(X_train, y_train, epochs=20)`,
    codeDescription: "Pixel values are divided by 255 to bring them into a 0 to 1 range before training. The network stacks convolutional layers to pick up on shapes and patterns, then flattens the output into a dense layer for classification. Dropout randomly switches off 20% of neurons during training to stop the model from memorizing the training data.",
    screenshots: [],
    techStack: ["Python", "TensorFlow", "Keras", "CNN", "CIFAR-10", "Matplotlib", "NumPy", "PIL", "Google Colab"],
    challenges: "Most of the concepts here were brand new. Epochs, dropout, image normalization, and how convolutional layers actually work all had to be understood from scratch. Working with images instead of spreadsheet data was new.",
    reflection: "This was the activity that made the machine learning field feel a lot bigger. Seeing the model correctly identify a cat or an airplane from an image I uploaded myself was cool I thought, and also made me realize that ML can be more than numbers in a table.",
    color: "bg-[oklch(0.85_0.12_340)]" // Pastel Pink
  },
  {
    slug: "dogs-vs-cats-cnn",
    title: "Dogs vs Cats CNN",
    description: "A school activity that classifies images as either a dog or a cat, then deploys the model as a web app using Flask and TFLite.",
    overview: "Same CNN workflow as the CIFAR-10 activity, but now just dog or cat. The model was loaded from a pre-trained weights file, connected to an Anvil frontend for live image uploads, and then exported as a TFLite model for Flask deployment. Having done CNNs before made the architecture feel familiar, so the focus this time was more on the deployment side.",
    features: [
      "Binary Image Classification with CNN",
      "Batch Normalization for Stable Training",
      "Dropout Regularization Across Multiple Layers",
      "Live Image Classification via Anvil UI",
      "Model Export to TFLite Format",
      "Web App Deployment with Flask"
    ],
    codeSnippet: `# Load pre-trained weights and run a prediction
    model.load_weights('/content/drive/MyDrive/Colab Notebooks/PTF04/cnn_model.h5')

    def get_prediction(test_img):
        test_img = test_img.resize((128,128), resample=PIL.Image.BICUBIC)
        test_arr = img_to_array(test_img)
        test_arr = np.expand_dims(test_arr, axis=0)
        test_arr /= 255.0
        return float(model.predict(test_arr))

    # Export to TFLite for deployment
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()

    with open('model.tflite', 'wb') as f:
        f.write(tflite_model)`,
    codeDescription: "The model loads pre-trained weights instead of training from scratch. Predictions are made by resizing the image, normalizing pixel values, and running it through the model. A score below 0.5 means dog, above 0.5 means cat. The TFLite export compresses the model into a format that runs efficiently in a Flask web app.",
    screenshots: [],
    techStack: ["Python", "TensorFlow", "Keras", "CNN", "TFLite", "Flask", "Anvil", "PIL", "NumPy", "Google Colab"],
    challenges: "TFLite was the one new thing here. Converting and exporting the model took some figuring out, but since everything else was familiar from the CIFAR-10 activity, it was easier to focus on just that part.",
    reflection: "This activity made it clear that different problems require different model setups. I learned when to use a binary classifier and a multi-class one, when to use sigmoid versus softmax, and when to use binary crossentropy versus categorical.",
    color: "bg-[oklch(0.88_0.10_80)]" // Pastel Yellow
  },
  {
    slug: "facemesh-filter-camera",
    title: "Facemesh Filter Camera",
    description: "A school activity that uses facial landmark detection to build a real-time face filter app in MIT App Inventor.",
    overview: "This activity used MIT App Inventor to build a face filter camera app, similar to how Snapchat and Instagram filters work. Using FaceExtension and a technology called Facemesh, the app maps points on a user's face in real time and uses those coordinates to position images like cat nose and ears on the correct spots. It was built using block-based, low-code programming instead of a traditional coding environment.",
    features: [
      "Real-time Facial Landmark Detection via Facemesh",
      "Face Mapping with FaceExtension",
      "Live Camera Feed with Overlay Positioning",
      "Block-based Low-code Development in MIT App Inventor"
    ],
    codeSnippet: `// Block: placeImage [ img ] [ facePoint ]
    // Moves an image sprite to a detected facial landmark coordinate

    to placeImage ( img, facePoint )
      call ImageSprite.MoveTo
        for component : get img
        x             : select list item [ get facePoint ] at index 1
        y             : select list item [ get facePoint ] at index 2`,
    codeDescription: "This block defines a reusable procedure that takes an image and a face point, then moves the image sprite to the X and Y coordinates of that landmark. Index 1 is the X position, index 2 is the Y position. Every time the face moves, this runs again and repositions the filter accordingly.",
    screenshots: [],
    techStack: ["MIT App Inventor", "FaceExtension", "Facemesh", "Block-based Programming"],
    challenges: "The environment was new since everything up to this point had been Python notebooks. MIT App Inventor works differently, but the instructions were clear and it was easy to pick up. The bigger adjustment was thinking in blocks instead of lines of code.",
    reflection: "Facemesh was interesting because it was the first time I worked with something fully live. The AI is not just analyzing a static image, it is actively tracking a person's face as they move. That felt different from everything else we had done, and it made me appreciate how much is happening under the hood in something as casual as a Snapchat filter.",
    color: "bg-[oklch(0.88_0.10_250)]" // Pastel Blue
  }
];
